apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: safe-client-gateway
  name: safe-client-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: safe-client-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: safe-client-gateway
    spec:
      containers:
        - image: sovryn/safe-client-gateway
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: safe-client-gateway
          - secretRef:
              name: safe-client-gateway-secret
          name: web
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: safe-client-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:768438872063:certificate/9fa02b26-0ee5-4301-bdd6-8474344885ff
spec:
  selector:
    app: safe-client-gateway
  ports:
    - port: 443
      targetPort: 8000
  type: LoadBalancer
---
