---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "safe-client-gateway.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "safe-client-gateway.name" . }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: config
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile: 
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- else }}
        resources:
          limits:
            cpu: 2000m
            memory: 8192Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "safe-client-gateway.fullname" . }}
          - secretRef:
              {{- if .Values.config.secretReferenceKey }}
              name: {{ .Values.config.secretReferenceKey }}
              {{- else }}
              name: {{ include "safe-client-gateway.fullname" . }}
              {{- end }}
          - secretRef:
              name: {{ include "safe-client-gateway.redis-secret" . }}
          - secretRef:
              name: {{ include "safe-client-gateway.redis-mainnet-secret" . }}
        ports:
        - containerPort: {{ .Values.service.ports.number }}
          name: {{ .Values.service.ports.name }}
          protocol: TCP
        # volumeMounts:
        #   - name: tmp-volume
        #     mountPath: /tmp
      serviceAccountName: {{ include "safe-client-gateway.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # volumes:
      #   - name: tmp-volume
      #     emptyDir: {} 

