apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
  annotations:
  {{- if .Values.commonAnnotations }}
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
                service:
                    name: {{ include "safe-client-gateway.fullname" . }}
                    port:
                        name: {{ .Values.service.ports.name }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.hostname }}-tls
