{{- if not .Values.config.secretReferenceKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  ROCKET_SECRET_KEY: {{ .Values.config.secretKey | b64enc }}
  WEBHOOK_TOKEN: {{ .Values.config.webToken | b64enc }}
  TRANSACTION_SERVICE_AUTH_TOKEN: {{ .Values.config.transactionServiceToken | b64enc }}
  #EXCHANGE_API_KEY: your_exchange_rate_api_token


{{- end }}
