---
{{- if not .Values.config.redis.secretReferenceKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  # Format redis://redis-ha.redis.svc.cluster.stage:6379/0 
  REDIS_URI: "{{- printf "redis://%s@%s:%s" .Values.config.redis.password .Values.config.redis.host .Values.config.redis.port | b64enc -}}"
{{- end }}