apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-client-gateway-helm.fullname" . }}
  labels:
    {{- include "safe-client-gateway-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "safe-client-gateway-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "safe-client-gateway-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "safe-client-gateway-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROCKET_PORT
              value: "80"
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
            - name: ROCKET_LOG_LEVEL
              value: normal
            - name: SCHEME
              value: http
            - name: WEBHOOK_TOKEN
              value: {{ required "Require .Values.safeClientGateway.webhookToken" .Values.safeClientGateway.webhookToken }}
            - name: INTERNAL_CLIENT_CONNECT_TIMEOUT
              value: "10000"
            - name: SAFE_APP_INFO_REQUEST_TIMEOUT
              value: "10000"
            - name: CHAIN_INFO_REQUEST_TIMEOUT
              value: "15000"
            - name: REDIS_URI
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master
            - name: EXCHANGE_API_BASE_URI
              value: http://api.exchangeratesapi.io/latest
            - name: LOG_ALL_ERROR_RESPONSES
              value: "true"
            - name: CONFIG_SERVICE_URI
              value: {{ required "Require .Values.safeClientGateway.configServiceUri" .Values.safeClientGateway.configServiceUri }}
            - name: ROCKET_SECRET_KEY
              value: {{ required "Require .Values.safeClientGateway.rocketSecretKey" .Values.safeClientGateway.rocketSecretKey }}
            - name: EXCHANGE_API_KEY
              value: {{ required "Require .Values.safeClientGateway.exchangeApiKey" .Values.safeClientGateway.exchangeApiKey }}
            - name: RUST_BACKTRACE
              value: "1"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
