base: 'http://localhost:8000'
iterations: 1

plan:
  - name: Fetch balances
    request:
      url: /v1/safes/{{ item.safe_address }}/balances/USD
    with_items_from_csv:
      file_name: ./safes.csv
      quote_char: "\""

  - name: Fetch collectibles
    request:
      url: /v1/safes/{{ item.safe_address }}/collectibles
    with_items_from_csv:
      file_name: ./safes.csv
      quote_char: "\""

  - name: Fetch transactions/queued
    request:
      url: /v1/safes/{{ item.safe_address }}/transactions/queued
    with_items_from_csv:
      file_name: ./safes.csv
      quote_char: "\""

  - name: Fetch transactions/history
    request:
      url: /v1/safes/{{ item.safe_address }}/transactions/history
    with_items_from_csv:
      file_name: ./safes.csv
      quote_char: "\""